# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://selfcontrol.apki.io
author: Paweł Urbanek
description: iOS App inspired by a well known SelfControl, it aims to provide a similar functionality on iOS. It allows you to block distracting websites on iPhone. Have you ever wasted your time on the Internet? Having trouble getting stuff done because of procrastination? Do you need more self control? This is the app for you.
copyright: '&copy; Paweł Urbanek 2018'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

