# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://selfcontrol.apki.io
author: Paweł Urbanek
description: iOS App inspired by a well known SelfControl. It aims to provide a similar functionality on iOS. It allows you to block distracting websites on your iPhone. Have you ever wasted your time on the Internet? Having trouble getting stuff done because of procrastination? Do you need more self control?
copyright: '&copy; Paweł Urbanek 2021'
preview_image: /img/icon.png
keywords: SelfControl, Self Control, mobile addiction, block facebook, distracting websites, iphone addiction, ios
title: SelfControl App for iPhone | Block Websites on iOS
lifehacker_link: https://lifehacker.com/self-control-the-brute-force-distraction-blocker-land-1791430018
appstore_link: https://itunes.apple.com/us/app/control-procrastination-block-distracting-websites/id1189844594?mt=8&at=1001lxGu&ct=wll

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

